---
- name: check if sshd_config.d exits
  stat:
    path: /etc/ssh/sshd_config.d
  register: sshd_config_d_exists

- name: configure sshd
  become: 'yes'
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify:
    - restart sshd
  tags:
    - sshd_config
    - sshd

- name: sshd host keys
  become: 'yes'
  find:
    paths: /etc/ssh
    file_type: file
    patterns: 'ssh_host_*'
    excludes: '*.pub'
  register: ssh_host_keys
  tags:
    - sshd

- name: sshd host key permissions
  become: 'yes'
  file:
    owner: root
    group: root
    mode: 0600
    path: "{{ item.path }}"
  with_items: "{{ ssh_host_keys.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags:
    - sshd

- name: check if ssh_config.d exits
  stat:
    path: /etc/ssh/ssh_config.d
  register: ssh_config_d_exists

- name: configure ssh client
  become: 'yes'
  template:
    src: etc/ssh/ssh_config.j2
    dest: /etc/ssh/ssh_config
    backup: 'yes'
    mode: 0644
    owner: root
    group: root
  tags:
    - ssh_config
    - ssh
...
