---
- name: remove users
  become: 'yes'
  user:
    name: "{{ item }}"
    state: absent
    remove: 'yes'
  with_items:
    - games
    - gnats
    - irc
    - list
    - news
    - sync
    - uucp
  ignore_errors: true
  tags:
    - users

- name: find user /home directories
  find:
    paths: /home
    file_type: directory
  register: home_directories
  tags:
    - users

- name: set user /home directories permission
  become: 'yes'
  file:
    mode: 0750
    path: "{{ item.path }}"
  with_items: "{{ home_directories.files }}"
  loop_control:
    label: "{{ item.path }}"
  tags:
    - users
...
